download = false

[database]
location = "motherduck"
name = "autostyl"
type = "duckdb"
# location = "gcp"

[datasets.frames]
type = image
[datasets.galleries]
type = image

[pinterest.labels]
location = 'labels.json'
prefer = ['colour', 'recent']
amount = 10 
[instagram.labels]
location = 'labels.json'
prefer = ['colour', 'recent']
amount = 10

[pinterest]
table = "Dataset" # the table to insert into 
